import localFont from "next/font/local";

import "./globals.css";

const clashDisplay = localFont({
  src: "./fonts/ClashDisplay_Complete/Fonts/WEB/fonts/ClashDisplay-Variable.woff2",
  weight: "100 200 300 400 500 600 700 800 900",
  variable: "--font-clash-display",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${clashDisplay.variable}`}>
      <body>{children}</body>
    </html>
  );
}
